export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";
export const FETCH_PRODUCT_REQUEST_SUCCESS = "FETCH_PRODUCT_REQUEST_SUCCESS";
export const FETCH_PRODUCT_REQUEST_FAIL = "FETCH_PRODUCT_REQUEST_FAIL";
