export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const ADD_QUANTITY = "ADD_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const FINALIZE_PURCHASE = "FINALIZE_PURCHASE";
export const CANCEL_PURCHASE = "CANCEL_PURCHASE";
